package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html class=\"no-js\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <title>Clinix</title>\n");
      out.write("    \n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta content=\"yes\" name=\"apple-mobile-web-app-capable\" />\n");
      out.write("    <meta name=\"viewport\" content=\"minimum-scale=1.0, width=device-width, maximum-scale=1, user-scalable=no\" />\n");
      out.write("\n");
      out.write("   \n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style/flexslider.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style/animations.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style/font-awesome.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style/jquery.flickr.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style/prettyPhoto.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"style/home.css\">\n");
      out.write("\n");
      out.write("    <script src=\"js/modernizr-2.6.2-respond-1.1.0.min.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <a href=\"logout.jsp\">Sign Out</a>\n");
      out.write("    ");
 
        String username=(String)session.getAttribute("username");
     if(username==null || username.trim().equals("")) 
     {
      response.sendRedirect("login.html");
     }
    
      out.write("\n");
      out.write("   \n");
      out.write("\n");
      out.write(" \n");
      out.write("    <div class=\"offsetWrap\">\n");
      out.write("\n");
      out.write("        <div class=\"offsetMaker\">\n");
      out.write("\n");
      out.write("            <header class=\"bg-white doc-header\">\n");
      out.write("                <div class=\"head-contact clearfix\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <ul class=\"nav-top pull-left\">\n");
      out.write("                          <h1>Hello ");
      out.print(username);
      out.write("..!</h1>\n");
      out.write("                            \n");
      out.write("                           \n");
      out.write("                             \n");
      out.write("                        </ul>\n");
      out.write("\n");
      out.write("                        <ul class=\"contact pull-right\">\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-phone\"></i>0800-1234-567</a></li>\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-envelope\"></i>info@clinix.com</a></li>\n");
      out.write("                        </ul>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <nav id=\"sticktop\">\n");
      out.write("                    <div class=\"container\">\n");
      out.write("\n");
      out.write("                        <a href=\"index.html\" class=\"text-left logo\"><img src=\"img/Latest loogoo.png\"\n");
      out.write("                                width=\"150\" alt=\"\" title=\"Homepage\"></a>\n");
      out.write("                        <ul class=\"socials\">\n");
      out.write("                            <li><a href=\"#\" class=\"fb\"><i class=\"fa fa-facebook-f\"></i></a></li>\n");
      out.write("                            <li><a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("                        </ul>\n");
      out.write("                        <a href=\"#\" class=\"nav-triger\"><span class=\"fa fa-navicon\"></span></a>\n");
      out.write("                        <ul class=\"main-menu\">\n");
      out.write("                            <li class=\"active\">\n");
      out.write("                            \n");
      out.write("\n");
      out.write("                            <li><a href=\"about-us.html\">About Us</a></li>\n");
      out.write("                            <li><a href=\"contact-us.html\">Contact</a></li>\n");
      out.write("        \n");
      out.write("                            \n");
      out.write("                            <li><script src=\"https://cdn.lordicon.com/bhenfmcm.js\"></script>\n");
      out.write("                            <lord-icon src=\"https://cdn.lordicon.com/lqsduwhb.json\" trigger=\"hover\"\n");
      out.write("                                colors=\"primary:#121331\" state=\"hover-2\" style=\"width:50px;height:50px\">\n");
      out.write("                            </lord-icon></li> \n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("            </header>\n");
      out.write("\n");
      out.write("            <section class=\"custom-slider no-pad\">\n");
      out.write("                <div id=\"home-slider\" class=\"xv_slider flexslider\">\n");
      out.write("                    <ul class=\"slides\">\n");
      out.write("                        <li class=\"xv_slide\" data-slideBg=\"url(img/sld1.jpg)\">\n");
      out.write("                            <div class=\"flex-caption\">\n");
      out.write("                                <div class=\"container\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-md-offset-7 col-md-5 col-sm-6 col-sm-offset-6\">\n");
      out.write("                                            <h3\n");
      out.write("                                                class=\"mb-25 text-uppercase color-blue text-bold after-left-l pb-30 animated fadeInLeft\">\n");
      out.write("                                                ONLINE CONSULTATION.\n");
      out.write("                                            </h3>\n");
      out.write("                                            <p class=\"animated fadeInRight\">Get help via an online video call and\n");
      out.write("                                                receive your e-Prescriptions, lab requests, medical certificates,\n");
      out.write("                                                receive your lab results, purchase medicines without going to the\n");
      out.write("                                                pharmacy and more.</strong> </p>\n");
      out.write("                                            <a href=\"appointment.html\" class=\"btn animated fadeInUp\">CLICK HERE\n");
      out.write("                                                <h6 class=\"t-white\">Book Appointment Now!</h6>\n");
      out.write("                                            </a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"xv_slide\" data-slideBg=\"url(img/s2.jpg)\">\n");
      out.write("                            <div class=\"flex-caption\">\n");
      out.write("                                <div class=\"container\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-md-offset-7 col-md-5 col-sm-6 col-sm-offset-6\">\n");
      out.write("                                            <h3\n");
      out.write("                                                class=\"mb-25 text-uppercase color-blue text-bold after-left-l pb-30 animated fadeInLeft\">\n");
      out.write("                                                INTERACTIVE VIDEO CALL SESSIONS\n");
      out.write("                                            </h3>\n");
      out.write("                                            <p class=\"animated fadeInRight\">Get help via an online video call and\n");
      out.write("                                                receive your e-Prescriptions, lab requests, medical certificates,\n");
      out.write("                                                receive your lab results, purchase medicines without going to the\n");
      out.write("                                                pharmacy and more.</strong> </p>\n");
      out.write("                                            <a href=\"appointment.html\" class=\"btn animated fadeInUp\">CLICK HERE\n");
      out.write("                                                <h6 class=\"t-white\">Book Appointment Now!</h6>\n");
      out.write("                                            </a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </li>\n");
      out.write("\n");
      out.write("                        <li class=\"xv_slide\" data-slideBg=\"url(img/s1.jpg)\">\n");
      out.write("                            <div class=\"flex-caption\">\n");
      out.write("                                <div class=\"container\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-md-offset-7 col-md-5 col-sm-6 col-sm-offset-6\">\n");
      out.write("                                            <h3\n");
      out.write("                                                class=\"mb-25 text-uppercase color-blue text-bold after-left-l pb-30 animated fadeInLeft\">\n");
      out.write("                                                ONLINE PRESCRIPTION BY TRUSTED DOCTORS\n");
      out.write("                                            </h3>\n");
      out.write("                                            <p class=\"animated fadeInRight\">Get help via an online video call and\n");
      out.write("                                                receive your e-Prescriptions, lab requests, medical certificates,\n");
      out.write("                                                receive your lab results, purchase medicines without going to the\n");
      out.write("                                                pharmacy and more.</p>\n");
      out.write("                                            <a href=\"appointment.html\" class=\"btn animated fadeInUp\">CLICK HERE\n");
      out.write("                                                <h6 class=\"t-white\">Book Appointment Now!</h6>\n");
      out.write("                                            </a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("            <section class=\"services bg-blue color-white no-pad clearfix\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 service no-pad style1 bg-blue1\">\n");
      out.write("                            <h6 class=\"text-uppercase text-bold after-left-s pb-45 mb-15\"><img\n");
      out.write("                                    src=\"img/i6.png\" class=\"pull-left\" alt=\"/\"><span class=\"pad\">HEART<br>\n");
      out.write("                                    SPECIALIST</span></h6>\n");
      out.write("                            <p>We have treatment for heart related deasease.</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 service no-pad style2 bg-blue2\">\n");
      out.write("                            <h6 class=\"text-uppercase text-bold after-left-s pb-45 mb-15\"><img\n");
      out.write("                                    src=\"img/i2.png\" class=\"pull-left\" alt=\"/\"><span class=\"pad\">CHILD<br>\n");
      out.write("                                    SPECIALIST</span></h6>\n");
      out.write("                            <p>Child care information and prescription.</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 service no-pad style3 bg-blue3\">\n");
      out.write("                            <h6 class=\"text-uppercase text-bold after-left-s pb-45 mb-15\"><img\n");
      out.write("                                    src=\"img/i1.png\" class=\"pull-left\" alt=\"/\"><span class=\"pad\">DNA<br>\n");
      out.write("                                    LABORATORY</span></h6>\n");
      out.write("                            <p>Let us take care of your eyes with new technology.</p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-3 col-sm-6 service no-pad style4 bg-blue4\">\n");
      out.write("                            <h6 class=\"text-uppercase text-bold after-left-s pb-45 mb-15\"><img\n");
      out.write("                                    src=\"img/i3.png\" class=\"pull-left\" alt=\"/\"><span class=\"pad\">TOOTH<br>\n");
      out.write("                                    SPECIALIST</span></h6>\n");
      out.write("                            <p>teeth pain remedies are also available.</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("            <section class=\"clearfix animatedParent\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-md-7 col-sm-6\">\n");
      out.write("                            <h3 class=\"text-bold after-left-l pb-25 mb-55\">About Us</h3>\n");
      out.write("                            <p>Doctor Web is a preventative health care, exercise/diet program, and regular examinations\n");
      out.write("                                tool that can help you enjoy a lifetime of good health.</p>\n");
      out.write("                            <p>We can provide the closest prescription of the deasease you are having, its an AI\n");
      out.write("                                generated prescription which is dependent on the symptoms of the patient.</p><br>\n");
      out.write("                            <p>Doctor Web is built in a manner that it will detect the diseases and provide the proper\n");
      out.write("                                medication .</p>\n");
      out.write("                              <a href=\"#\" class=\"btn mt-25\">Read More</a> \n");
      out.write("                        </div>\n");
      out.write("                          <div class=\"col-md-5 col-sm-6 schedules\">\n");
      out.write("                        <h3 class=\"text-bold after-left-l pb-25 mb-55 ls-5\">SCHEDULE</h3>\n");
      out.write("\n");
      out.write("                        <div class=\"schedule bg-blue1 radius-top color-white clearfix\">\n");
      out.write("                            <h6 class=\"text-uppercase text-bold pull-left\"><img src=\"img/i6.png\" class=\"pull-left\" alt=\"/\"><span class=\"pad\">SCHEDULE <br> TITLE</span></h6>\n");
      out.write("                            <div class=\"pull-right text-center\">\n");
      out.write("                                <strong>MON - WED</strong><br>\n");
      out.write("                                10:00 AM -7:00 PM\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"schedule bg-blue2 color-white clearfix\">\n");
      out.write("                            <h6 class=\"text-uppercase text-bold pull-left\"><img src=\"img/i5.png\" class=\"pull-left\" alt=\"/\"><span class=\"pad\">SCHEDULE <br> TITLE</span></h6>\n");
      out.write("                            <div class=\"pull-right text-center\">\n");
      out.write("                                <strong>MON - WED</strong><br>\n");
      out.write("                                10:00 AM -7:00 PM\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"schedule bg-blue3 color-white clearfix\">\n");
      out.write("                            <h6 class=\"text-uppercase text-bold pull-left\"><img src=\"img/i4.png\" class=\"pull-left\" alt=\"/\"><span class=\"pad\">SCHEDULE <br> TITLE</span></h6>\n");
      out.write("                            <div class=\"pull-right text-center\">\n");
      out.write("                                <strong>MON - WED</strong><br>\n");
      out.write("                                10:00 AM -7:00 PM\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"schedule bg-blue4 radius-bottom color-white clearfix\">\n");
      out.write("                            <h6 class=\"text-uppercase text-bold pull-left\"><img src=\"img/i3.png\" class=\"pull-left\" alt=\"/\"><span class=\"pad\">SCHEDULE <br> TITLE</span></h6>\n");
      out.write("                            <div class=\"pull-right text-center\">\n");
      out.write("                                <strong>MON - WED</strong><br>\n");
      out.write("                                10:00 AM -7:00 PM\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div> \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("            <section class=\"clearfix features text-center animatedParent\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <h2 class=\"text-bold text-uppercase color-blue after-mid-l pb-25\">\n");
      out.write("                        WHAT WE DO\n");
      out.write("                    </h2>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-sm-4 mt-70 animated fadeInLeft\">\n");
      out.write("                            <figure><img src=\"img/insulin.jpg\" alt=\"/\"></figure>\n");
      out.write("                            <h5 class=\"text-bold color-blue\">Diabetes Discipline</h5>\n");
      out.write("                            <p>We will help you eat sweets as much as you want. </p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-4 mt-70 animated fadeInLeft\">\n");
      out.write("                            <figure><img src=\"img/heart9.jpg\" alt=\"/\"></figure>\n");
      out.write("                            <h5 class=\"text-bold color-blue\">Heart Care</h5>\n");
      out.write("                            <p>We will help you to have a healthy heart. </p>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-4 mt-70 animated fadeInLeft\">\n");
      out.write("                            <figure><img src=\"img/brain99.jpg\" alt=\"/\"></figure>\n");
      out.write("                            <h5 class=\"text-bold color-blue\">Brain Functioning</h5>\n");
      out.write("                            <p>We will help you utilize your brain to fullest. </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("            <section class=\"clearfix reviews animatedParent\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <h3 class=\"text-bold text-uppercase after-left-l pb-25\">PATIENT REVIEWS</h3>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-sm-4 mt-50 animated fadeInLeft\">\n");
      out.write("                            <div class=\"review\">\n");
      out.write("                                <figure><img src=\"img/t1.png\" alt=\"/\"></figure>\n");
      out.write("                                <h5 class=\"text-bold color-blue\">Sara says...</h5>\n");
      out.write("                                <p>It was the smoothest implementation process I have ever been through. With Higher\n");
      out.write("                                    One?s process and schedule.</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-4 mt-50 animated fadeInLeft\">\n");
      out.write("                            <div class=\"review\">\n");
      out.write("                                <figure><img src=\"img/t2.jpg\" alt=\"/\"></figure>\n");
      out.write("                                <h5 class=\"text-bold color-blue\">Mike says...</h5>\n");
      out.write("                                <p>It was the smoothest implementation process I have ever been through. With Higher\n");
      out.write("                                    One?s process and schedule.</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-4 mt-50 animated fadeInLeft\">\n");
      out.write("                            <div class=\"review\">\n");
      out.write("                                <figure><img src=\"img/t3.jpg\" alt=\"/\"></figure>\n");
      out.write("                                <h5 class=\"text-bold color-blue\">Emma says...</h5>\n");
      out.write("                                <p>It was the smoothest implementation process I have ever been through. With Higher\n");
      out.write("                                    One?s process and schedule.</p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("              <section class=\"clearfix bg-white our-doctors animatedParent\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <h3 class=\"text-bold text-center text-uppercase after-mid-l pb-25\">OUR DOCTORS</h3>\n");
      out.write("                <p class=\"text-center mt-20\">Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>\n");
      out.write("                <div class=\"row color-white\">\n");
      out.write("                    <div class=\"col-sm-3 mt-50 no-pad doctor style1 bg-blue1 animated fadeInLeft\">\n");
      out.write("                        <figure><img src=\"img/dm.jpg\" alt=\"/\"></figure>\n");
      out.write("                        <div class=\"info\">\n");
      out.write("                        <h6 class=\"text-bold text-uppercase after-left-s pb-20\">Sara Doe</h6>\n");
      out.write("                        <p>Tooth Specialist</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-3 mt-50 no-pad doctor style2 bg-blue2 animated fadeInLeft\">\n");
      out.write("                        <div class=\"info\">\n");
      out.write("                        <h6 class=\"text-bold text-uppercase after-left-s pb-20\">John Doe</h6>\n");
      out.write("                        <p>Heart Specialist</p>\n");
      out.write("                        </div>\n");
      out.write("                        <figure><img src=\"img/d12.jpg\" alt=\"/\"></figure>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-3 mt-50 no-pad doctor style1 bg-blue3 animated fadeInLeft\">\n");
      out.write("                        <figure><img src=\"img/d22.jpg\" alt=\"/\"></figure>\n");
      out.write("                        <div class=\"info\">\n");
      out.write("                        <h6 class=\"text-bold text-uppercase after-left-s pb-20\">Umar Doe</h6>\n");
      out.write("                        <p>Eye Specialist</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-3 mt-50 no-pad doctor style2 bg-blue4 animated fadeInLeft\">\n");
      out.write("                        <div class=\"info\">\n");
      out.write("                        <h6 class=\"text-bold text-uppercase after-left-s pb-20\">Emma Doe</h6>\n");
      out.write("                        <p>Child Specialist</p>\n");
      out.write("                        </div>\n");
      out.write("                        <figure><img src=\"img/dr.jpg\" alt=\"/\"></figure>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("              <section class=\"our-posts\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <h3 class=\"text-bold text-uppercase after-mid-l pb-25 text-center\">PATIENT REVIEWS</h3>\n");
      out.write("                <p class=\"text-center\">Stay up to date with all our latest news and launches.</p>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-sm-4 mt-70\">\n");
      out.write("                        <div class=\"post bg-white\">\n");
      out.write("                            <figure><img src=\"img/962892_orig-480x340.jpg\" alt=\"/\"></figure>\n");
      out.write("                            <div class=\"pad\">\n");
      out.write("                            <a href=\"#\" class=\"title text-bold\">Doctor and Patient Doctors as Advocates for Family Leave</a>\n");
      out.write("                            <ul>\n");
      out.write("                                <li><i class=\"fa fa-clock-o\"></i>May 9, 2015</li>\n");
      out.write("                                <li><i class=\"fa fa-user\"></i><a href=\"#\">Mike</a></li>\n");
      out.write("                                <li><i class=\"fa fa-folder-open-o\"></i><a href=\"#\">Treatment</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                            <a href=\"#\" class=\"btn\">Read More</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-sm-4 mt-70\">\n");
      out.write("                        <div class=\"post bg-white\">\n");
      out.write("                            <figure><img src=\"img/bg-001-480x340.png\" alt=\"/\"></figure>\n");
      out.write("                            <div class=\"pad\">\n");
      out.write("                            <a href=\"#\" class=\"title text-bold\">Graphene?s Prospects in Biosensing Just Got a Boost</a>\n");
      out.write("                            <ul>\n");
      out.write("                                <li><i class=\"fa fa-clock-o\"></i>May 9, 2015</li>\n");
      out.write("                                <li><i class=\"fa fa-user\"></i><a href=\"#\">Mike</a></li>\n");
      out.write("                                <li><i class=\"fa fa-folder-open-o\"></i><a href=\"#\">Treatment</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                            <a href=\"#\" class=\"btn\">Read More</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"col-sm-4 mt-70\">\n");
      out.write("                        <div class=\"post bg-white\">\n");
      out.write("                            <figure><img src=\"img/doctor-compressor-480x340.jpg\" alt=\"/\"></figure>\n");
      out.write("                            <div class=\"pad\">\n");
      out.write("                            <a href=\"#\" class=\"title text-bold\">Your Phone Can Tell Whether You?re Depressed</a>\n");
      out.write("                            <ul>\n");
      out.write("                                <li><i class=\"fa fa-clock-o\"></i>May 9, 2015</li>\n");
      out.write("                                <li><i class=\"fa fa-user\"></i><a href=\"#\">Mike</a></li>\n");
      out.write("                                <li><i class=\"fa fa-folder-open-o\"></i><a href=\"#\">Treatment</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                            <a href=\"#\" class=\"btn\">Read More</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section> \n");
      out.write("\n");
      out.write("               <div class=\"promo bg-blue4 color-white clearfix pt-40 pb-40\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <span class=\"text-bold text-uppercase\">WHAT ARE YOU WAITING FOR</span>\n");
      out.write("                <a href=\"#\" class=\"btn\">Read More</a>\n");
      out.write("            </div>\n");
      out.write("        </div> \n");
      out.write("\n");
      out.write("            <footer class=\"bg-white pt-35\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-sm-3 mt-40\">\n");
      out.write("                            <h6 class=\"text-bold text-uppercase after-left-s pb-20 mb-20\">ABOUT DOCTOR WEB</h6>\n");
      out.write("                            <p>Our website is created to detect the normal and common deaseases,with the help of\n");
      out.write("                                symptoms.</p>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-sm-3 mt-40 tags\">\n");
      out.write("                            <h6 class=\"text-bold text-uppercase after-left-s pb-20 mb-20\">Tags</h6>\n");
      out.write("                            <a href=\"#\">care</a>\n");
      out.write("                            <a href=\"#\">website</a>\n");
      out.write("                            <a href=\"#\">doctor</a>\n");
      out.write("                            <a href=\"#\">heart</a>\n");
      out.write("                            <a href=\"#\">medicine</a>\n");
      out.write("                            <a href=\"#\">treatment</a>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"col-sm-3 mt-40 recent-posts\">\n");
      out.write("                            <h6 class=\"text-bold text-uppercase after-left-s pb-20 mb-20\">Recent posts</h6>\n");
      out.write("                            <ul>\n");
      out.write("                                <li><a href=\"#\">Doctor and Patient Doctors as Advocates for Family Leave</a></li>\n");
      out.write("                                <li><a href=\"#\">Graphene?s Prospects in Biosensing Just Got a Boost</a></li>\n");
      out.write("                                <li><a href=\"#\">Your Phone Can Tell Whether You?re Depressed</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-sm-3 mt-40\">\n");
      out.write("                            <h6 class=\"text-bold text-uppercase after-left-s pb-20 mb-20\">from flicker</h6>\n");
      out.write("                            <ul id=\"flicker-feed\" class=\"custom_flickr\" data-limit=\"6\" data-userID=\"52617155@N08\"></ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"rights mt-60 pt-15 pb-10\">\n");
      out.write("                        Made by <a>Aakansha,Ayush,Devesh</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </footer>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <script src=\"js/jquery.js\"></script>\n");
      out.write("    <script src=\"js/css3-animate-it.js\"></script>\n");
      out.write("    <script src=\"js/jquery.flexslider-min.js\"></script>\n");
      out.write("    <script src=\"js/jquery.sticky.js\"></script>\n");
      out.write("    <script src=\"js/jquery.waitforimages.js\"></script>\n");
      out.write("    <script src=\"js/jflickrfeed.min.js\"></script>\n");
      out.write("    <script src=\"js/jquery.prettyPhoto.js\"></script>\n");
      out.write("    <script src=\"https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false\"></script>\n");
      out.write("    <script src=\"js/main.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
